- name: set hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_ssh_host }} {{ hostname }}"
    state: present
  when: hostname is defined
