# How to allow or deny users the `cron` or `at` command.
# https://access.redhat.com/solutions/1535573
- name: set /etc/cron.allow
  file:
    path: /etc/cron.allow 
    state: "{{ 'absent' if cron_allow_everyone | bool else 'file' }}"
    mode: '600'
    access_time: preserve
    modification_time: preserve
 
- name: set /etc/cron.deny
  file:
    path: /etc/cron.deny
    state: "{{ 'touch' if cron_allow_everyone | bool else 'absent' }}"
    mode: '600' 
    access_time: preserve
    modification_time: preserve
