# clean repo dir
- name: find repo file
  find:
    path: /etc/yum.repos.d
    patterns: '*.repo'
  register: repo_to_delete

- name: delete repo file
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ repo_to_delete.files }}"
  changed_when: false

# kylin v10sp1 
- name: copy kylin v10sp1 repoflie
  template:
    src: "kylin_v10sp1.repo.j2"
    dest: "/etc/yum.repos.d/kylin_v10sp1_{{ ansible_architecture }}.repo"
  when: 
    - ansible_distribution == 'Kylin Linux Advanced Server'
    - ansible_distribution_major_version == 'V10'
    - ansible_distribution_release == 'Tercel'
  changed_when: false

# kylin v10sp2
- name: copy kylin v10sp2 repoflie
  template:
    src: "kylin_v10sp2.repo.j2"
    dest: "/etc/yum.repos.d/kylin_v10sp2_{{ ansible_architecture }}.repo"
  when: 
    - ansible_distribution == 'Kylin Linux Advanced Server'
    - ansible_distribution_major_version == 'V10'
    - ansible_distribution_release == 'Sword'
  changed_when: false

# kylin v7
- name: copy kylin v7 repoflie
  template:
    src: "kylin_v7.repo.j2"
    dest: "/etc/yum.repos.d/kylin_v7_{{ ansible_architecture }}.repo"
  when: 
    - ansible_distribution == 'RedHat'
    - "'V7' in ansible_distribution_major_version"
  changed_when: false

# rhel
- name: copy rhel repoflie
  template:
    src: "rhel_{{ ansible_distribution_major_version }}.repo.j2"
    dest: "/etc/yum.repos.d/rhel_{{ ansible_distribution_version }}_{{ ansible_architecture }}.repo"
  when: 
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8'
  changed_when: false
