- name: set /etc/security/limits.conf
  lineinfile:
    path: /etc/security/limits.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: true
  with_items:
    - regexp: '^\*\s+soft\s+core\s+'
      line: '* soft core {{ limit_soft_core }}'
    - regexp: '^\*\s+hard\s+core\s+'
      line: '* hard core {{ limit_hard_core }}'
    - regexp: '^\*\s+soft\s+nofile\s+'
      line: '* soft nofile {{ limit_soft_nofile }}'
    - regexp: '^\*\s+hard\s+nofile\s+'
      line: '* hard nofile {{ limit_hard_nofile }}'
    - regexp: '^\*\s+soft\s+nproc\s+'
      line: '* soft nproc {{ limit_soft_nproc }}'
    - regexp: '^\*\s+hard\s+nproc\s+'
      line: '* hard nproc {{ limit_hard_nproc }}'

- name: set /etc/systemd/system.conf
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: true
  with_items:
    - regexp: '^DefaultLimitCORE'
      line: 'DefaultLimitCORE={{ limit_soft_core }}:{{ limit_hard_core }}'
    - regexp: '^DefaultLimitNOFILE'
      line: 'DefaultLimitNOFILE={{ limit_soft_nofile }}:{{ limit_hard_nofile }}'
    - regexp: '^DefaultLimitNPROC'
      line: 'DefaultLimitNPROC={{ limit_soft_nproc }}:{{ limit_hard_nproc }}'
