- name: configure /etc/security/limits.conf
  pam_limits:
    domain: '*'
    limit_type: '-'
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  loop:
    - limit_item: core
      value: "{{ limit_core }}"
    - limit_item: nofile
      value: "{{ limit_nofile }}"
    - limit_item: nproc
      value: "{{ limit_nproc }}"

- name: set /etc/systemd/system.conf
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: true
  with_items:
    - regexp: '^DefaultLimitCORE'
      line: 'DefaultLimitCORE={{ limit_core }}:{{ limit_core }}'
    - regexp: '^DefaultLimitNOFILE'
      line: 'DefaultLimitNOFILE={{ limit_nofile }}:{{ limit_nofile }}'
    - regexp: '^DefaultLimitNPROC'
      line: 'DefaultLimitNPROC={{ limit_nproc }}:{{ limit_nproc }}'
